version: "3.9"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    deploy:
      replicas: 3
    networks:
      - frontend
    configs:
      - source: addressbook_nginx_conf
        target: /etc/nginx/conf.d/default.conf

networks:
  frontend:
    name: frontend
    external: true

configs:
  nginx_conf:
    external: true
